#!/bin/sh
set -e

case "$1" in
    configure)
        # Create rusty-beam user if it doesn't exist
        if ! getent passwd rusty-beam > /dev/null; then
            adduser --system --group --home /var/www/rusty-beam \
                --no-create-home --disabled-password \
                --gecos "Rusty Beam Server" rusty-beam
        fi

        # Set ownership of server root
        chown -R rusty-beam:rusty-beam /var/www/rusty-beam
        chmod 755 /var/www/rusty-beam

        # Set ownership of config directory
        chown -R rusty-beam:rusty-beam /etc/rusty-beam
        chmod 755 /etc/rusty-beam
        chmod 644 /etc/rusty-beam/config.html

        # Reload systemd
        systemctl daemon-reload || true
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

# Automatically added by dh_installsystemd/13.3.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'rusty-beam.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'rusty-beam.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'rusty-beam.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'rusty-beam.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.3.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'rusty-beam.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0