services:
  rusty-beam:
    build: .
    image: rusty-beam:latest
    container_name: rusty-beam-server
    ports:
      - "3000:3000"
    environment:
      # Google OAuth2 credentials
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_OAUTH2_CALLBACK=${GOOGLE_OAUTH2_CALLBACK}
      # Railway environment variables
      - PORT=${PORT}
      - RAILWAY_PUBLIC_DOMAIN=${RAILWAY_PUBLIC_DOMAIN}
      - RAILWAY_STATIC_URL=${RAILWAY_STATIC_URL}
      # Server configuration (currently not used since we're using the config file directly)
      - RUSTYBEAM_HOSTNAME=${RUSTYBEAM_HOSTNAME:-localhost}
      - RUSTYBEAM_PORT=${RUSTYBEAM_PORT:-3000}
      - RUSTYBEAM_BIND=${RUSTYBEAM_BIND:-0.0.0.0}
    volumes: []
    entrypoint: ["/app/docker-entrypoint.sh"]
    restart: "no"
    
    # For production, you might want to add:
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 512M